SET TERM ^ ;

CREATE TABLE MASTER_SUPPLIER
(
    ID INTEGER not null,
    SUPPLIER_NAME VARCHAR (150) not null,
    STATUS VARCHAR (1) NOT NULL,
    CREATED_DATE DATE,
    UPDATED_DATE DATE,

    PRIMARY KEY (ID)
)^

CREATE GENERATOR MASTER_SUPPLIER_GEN^

CREATE TRIGGER MASTER_SUPPLIER_BI FOR MASTER_SUPPLIER ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
if (new.id is null) then new.id = gen_id(MASTER_SUPPLIER_GEN,1); 
END^

SET TERM ; ^